spring:
  profiles:
    group:
      "local" : "local, oauth"
    active : local

logging:
  level:
    org:
      hiberante:
        SQL: debug

---
spring:
  config:
    activate:
      on-profile: "local"

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/oauthtest
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100 #배치 사이즈 (Collection 조회 최적화)

    hibernate:
      ddl-auto: create

